### ISSUE TITLE
Incompatible changes from 13.6.0 to 13.7.0

### ISSUE THREAD

**Issue by apetrelli** [checkstyle/eclipse-cs#1019]
Greetings,
I use Eclipse Checkstyle Plugin together with "Checkstyle configuration plugin for M2Eclipse" and I notice that, after upgrade from 13.6.0 to 13.7.0, there is a NoClassDefFoundError as stated in this issue:
https://github.com/m2e-code-quality/m2e-code-quality/issues/432

I noticed that you renamed the ICheckConfiguration interface to CheckConfiguration, causing it to be incompatible. I think you should reconsider such a breaking change, at least by using deprecations.

Thanks in advance.

**Comment by Calixte** [comment]
Sorry about that. Since the downstream project has not adopted the breaking change yet, I'm thinking of reverting it for version 13.8.0, and wait for version 14 to reintroduce it.
