### PR TITLE
Issue #322: NPE on rule configuration

### PR DESCRIPTION
**Pull request by Bananeweizen**
Issue #322

Broken since introduction of tokenTypesSet in
https://github.com/checkstyle/checkstyle/commit/d038f187190ee5c9d2d55b6aae985b3ec9327614 of the main checkstyle project.

### CODE REVIEW

**Comment by rnveach** [comment]
Is there something preventing adding tests for this code to ensure it is not broken in the future?

**Comment by Bananeweizen** [comment]
> Is there something preventing adding tests for this code to ensure it is not broken in the future?

Not really sure where to start adding tests there, that's an area of code I haven't been exploring before. I was rather thinking of adding more assertions for nonnull members for all the config classes, which would have detected this problem at the moment of using the new checkstyle version.

The failing tests are caused by #351, which is why I have finally taken time to fix that. All other open failing PRs would need to be rebased after that is merged.

**Comment by rnveach** [comment]
https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/587945887
Failure is the same as https://github.com/checkstyle/eclipse-cs/pull/377#issuecomment-1309710185 and should be fixed as soon as we release patch-filters and upgrade to it.

**Comment by romani** [comment]
Failure was
```
Caused by: java.lang.NoSuchMethodError: 'com.puppycrawl.tools.checkstyle.api.LocalizedMessage com.puppycrawl.tools.checkstyle.TreeWalkerAuditEvent.getLocalizedMessage()'
	at com.puppycrawl.tools.checkstyle.filters.JavaPatchFilterElement.isLineMatching(JavaPatchFilterElement.java:217)
```

Should be resolved after merge of https://github.com/checkstyle/eclipse-cs/pull/383 with upgrade of patch-filter to 1.2.0

**Comment by romani** [comment]
Travis failure
```
[INFO] --- maven-checkstyle-plugin:3.2.0:check (sevntu-checkstyle-check) @ net.sf.eclipsecs.core ---
[INFO] There is 1 error reported by Checkstyle 10.0 with config/checkstyle_sevntu_checks.xml ruleset.
[ERROR] src/net/sf/eclipsecs/core/config/meta/
MetadataFactory.java:[314,35] (extension) MultipleStringLiteralsExtended: 
The String "java.util.regex.Pattern" appears 2 times in the file.
```

Did you try to fix it? Does it avalanche of other complains from checkstyle?

**Review by romani — APPROVED** [review]
we need to agree on some way of sharing how it was tested (as we have no auto tests).
@Bananeweizen , please suggest a way.

for CS version bump commits, we agreed to share images that new Check/propertties is rendering  fine in UI and can produce violations.

**Comment by Bananeweizen** [comment]
I've reproduced the NPE by just adding the MagicNumber check to the list of active checks in the configuration UI. With this change, the NPE no longer happens. In fact, all checks can be added via the configuration UI now, without causing any exception. I'd rather like to write such a short sentence than posting some images, since images don't tell anything how to reproduce the testing.

**Comment by romani** [comment]
sounds like most easy way to reproduce a problem..... not sure why @Calixte did not run into it while shallow-testing of new CS version updates.

**Comment by Bananeweizen** [comment]
Well, everything worked okay if you would only try configuring something from the top of the list of checkers. Therefore I can understand he didn't notice. In fact, I also didn't run into the issue ever before, and I also did similar quick tests several times. (and at work with a real life config, I use the XML editor directly)
